name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, x64, aws]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Running on AWS EC2"
          docker --version
          uname -a